import Head from 'next/head';
import Image from 'next/image';
import Layout from '../component/Layout';
import styles from '../styles/Home.module.css';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { createContext, useContext, useState } from 'react';
import { Table } from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import Tables from '../pages/table';

export const store = createContext();

export default function Home() {
  const [name, setName] = useState('');
  const [Item, setItem] = useState([]);

  const addItemHandlar = () => {
    setItem([...Item, { name: name, id: Math.random() }]);
    setName('')
  };
  // console.log(Item);
  return (
    <store.Provider value={[Item, setItem]}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <TextField
            id="outlined-basic"
            label="Outlined"
            variant="outlined"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <Button sx={{ m: 1 }} variant="contained" onClick={addItemHandlar}>
            Submit
          </Button>
          <Tables />
        </Layout>
      </div>
    </store.Provider>
  );
}
